name: 'Build Nginx + WAF agent Docker image'

on:
  schedule:
    # 0513 AWST, Mon-Fri
    - cron: '13 21 * * 1-5'
  push:
    # Publish `main` as `latest` image.
    branches: [main]
    # Publish tags as releases.
    tags: ['*']
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/nginx-sigsci

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    permissions:
      attestations: write
      actions: read
      checks: write
      contents: read
      deployments: none
      id-token: write
      issues: read
      discussions: read
      packages: write
      pages: none
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read

    # The job runs on different runners based on the platform.
    # For linux/amd64, it runs on the latest Ubuntu runner.
    # For linux/arm64, it runs on an Ubuntu 24.04 ARM runner.
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' }}
    name: Build Nginx+WAF agent image for ${{ matrix.platform }}
    steps:
      #----------------------------------------------
      # This step sets up the environment for the current platform being built.
      # The environment variable PLATFORMS_PAIR will be used later in the workflow.
      #----------------------------------------------
      - name: Prepare environment for current platform
        id: prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      #----------------------------------------------
      # Make use of the Step Security Harden Runner workflow to monitor the build process.
      #----------------------------------------------
      - name: Harden the GitHub runner
        uses: step-security/harden-runner@v2.14.0
        with:
          egress-policy: audit

      #----------------------------------------------
      # Checkout repo
      #----------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      #----------------------------------------------
      # Generates metadata for the Docker image.
      #----------------------------------------------
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      #----------------------------------------------
      # Set up a Docker context for Buildx.
      #----------------------------------------------
      - name: Set up Docker Buildx
        id: buildx-context
        run: |
          docker context create builders

      #----------------------------------------------
      # Set up Docker Buildx, which is a Docker CLI plugin for extended build capabilities with BuildKit.
      #----------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
          platforms: ${{ matrix.platform }}

      #----------------------------------------------
      # Log Docker into the GitHub Container Repository
      #----------------------------------------------
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #----------------------------------------------
      # This step builds and pushes the Docker image using Buildx.
      # The outputs are configured to push the image by digest, which allows for better caching and versioning.
      #----------------------------------------------
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: Dockerfile.nginx
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true,oci-mediatypes=true
          cache-from: type=gha,scope=${{ github.repository }}-${{ github.ref_name }}-${{ matrix.platform }}
          cache-to: type=gha,scope=${{ github.repository }}-${{ github.ref_name }}-${{ matrix.platform }}

      #----------------------------------------------
      # This step exports the digest of the built image to a file.
      # It creates a directory in /tmp/digests and saves the digest of the image to a file.
      #----------------------------------------------
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      #----------------------------------------------
      # This step uploads the digest file to the GitHub Actions artifact storage.
      # The artifact is named digests-${{ env.PLATFORM_PAIR }}, where PLATFORM_PAIR is the platform name with '/' replaced by '-'.
      # The artifact is retained for 1 day, and if no files are found, it will throw an error.
      #----------------------------------------------
      - name: Upload digest
        uses: actions/upload-artifact@v6
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          retention-days: 1
          if-no-files-found: error

  merge:
    name: Merge Docker image manifests
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      actions: read
      checks: read
      contents: read
      deployments: none
      id-token: write
      issues: read
      discussions: read
      packages: write
      pages: none
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    needs:
      - build
    steps:
      #----------------------------------------------
      # This step downloads the digest files uploaded in the build job.
      # It uses the actions/download-artifact action to download the artifacts with the pattern digests-*.
      # The downloaded files are merged into the /tmp/digests directory.
      #----------------------------------------------
      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      #----------------------------------------------
      # This step generates metadata for the Docker image.
      # It uses the docker/metadata-action to create metadata based on the repository information.
      # The metadata includes information such as the image name, tags, and labels.
      #----------------------------------------------
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          annotations: |
            type=org.opencontainers.image.description,value=${{ github.event.repository.description || 'No description provided' }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{version}}

      #----------------------------------------------
      # Set up Docker Buildx.
      #----------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #----------------------------------------------
      # This step gets the current execution timestamp in RFC3339 format.
      # It uses the date command to get the current UTC time and formats it as a string.
      # The timestamp is used for annotating the Docker manifest list.
      #----------------------------------------------
      - name: Get execution timestamp with RFC3339 format
        id: timestamp
        run: |
          echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      #----------------------------------------------
      # This step creates a manifest list for the Docker images built for different platforms.
      # The manifest list is annotated with metadata such as description, creation timestamp, and source URL.
      # The annotations are obtained from the metadata generated in the previous steps.
      # The manifest list is pushed to the container registry with the specified tags.
      #----------------------------------------------
      - name: Create manifest list and pushs
        working-directory: /tmp/digests
        id: manifest-annotate
        continue-on-error: true
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            --annotation='index:org.opencontainers.image.description=${{ github.event.repository.description }}' \
            --annotation='index:org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}' \
            --annotation='index:org.opencontainers.image.url=${{ github.event.repository.url }}' \
            --annotation='index:org.opencontainers.image.source=${{ github.event.repository.url }}' \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)

      #----------------------------------------------
      # This step creates a manifest list for the Docker images built for different platforms.
      # The manifest list is pushed to the container registry with the specified tags.
      #----------------------------------------------
      - name: Create manifest list and push without annotations
        if: steps.manifest-annotate.outcome == 'failure'
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create  $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)

      #----------------------------------------------
      # This step inspects the created manifest list to verify its contents.
      #----------------------------------------------
      - name: Inspect image
        id: inspect
        run: |
          docker buildx imagetools inspect '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}'
